// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Beef struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Meatcut   string
	Price     float64
	Quantitiy sql.NullFloat64
}
