// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Meatprice struct {
	ID         string
	CreatedAt  string
	UpdatedAt  string
	MeatSource string
	Meatcut    string
	Price      float64
}

type Order struct {
	ID         string
	CreatedAt  string
	UpdatedAt  string
	UserID     string
	MeatSource string
	Meatcut    string
	Price      float64
	Quantitiy  float64
}

type User struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Username  string
	Email     string
	IsAdmin   bool
}
